# name: Run Selenium Tests

# on:
#   push:
#     branches:
#       - main  # Run tests on the main branch when changes are pushed

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     services:
#       selenium:
#         image: selenium/standalone-chrome
#         ports:
#           - 4444:4444

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: '3.x'

#       - name: Install dependencies
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install selenium pytest pytest-html

#       - name: Run Selenium tests
#         run: |
#           source venv/bin/activate
#           pytest --html=report.html --self-contained-html
          
#       - name: Upload report
#         uses: actions/upload-artifact@v3
#         with:
#           name: test-report
#           path: report.html
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: report.html
